apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: che
  name: che-data-volume
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
